// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXwzSvpKHiG6iDPJ6OWVVqqK3bcbTLUw',
    appId: '1:114291809633:android:825f6ed8c262170ce03920',
    messagingSenderId: '114291809633',
    projectId: 'flutter-app-distribution-db17a',
    storageBucket: 'flutter-app-distribution-db17a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB59c3CfufvoxKZG-k_AwRS4UE3u-E8rcE',
    appId: '1:114291809633:ios:1bcb02e62415a2dae03920',
    messagingSenderId: '114291809633',
    projectId: 'flutter-app-distribution-db17a',
    storageBucket: 'flutter-app-distribution-db17a.firebasestorage.app',
    iosBundleId: 'com.example.complet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPH4Ykpc4qtOEY5Rejev1SwTx_k1XOiZI',
    appId: '1:114291809633:web:3ce8c47b40fc4477e03920',
    messagingSenderId: '114291809633',
    projectId: 'flutter-app-distribution-db17a',
    authDomain: 'flutter-app-distribution-db17a.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-db17a.firebasestorage.app',
    measurementId: 'G-1ELFM8LDRW',
  );

}