default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    firebase_app_distribution(
      app: "1:114291809633:android:825f6ed8c262170ce03920",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      release_notes: "Release notes for the latest build"
    )
  end
end
